---
# https://docs.openstack.org/ocata/install-guide-ubuntu/keystone-install.html#

# Wait for MySQL to be up and running
- name: db | Ensuring MySQL Is Up And Running
  wait_for:
    port: 3306

# Create Keystone DB
- name: db | Creating Keystone DB
  mysql_db:
    name: "{{ openstack_identity_service_keystone_db_info['db'] }}"
    state: "present"
  become: true

# Create Keystone DB user and grant privileges
- name: db | Creating Keystone DB User
  mysql_user:
    name: "{{ openstack_identity_service_keystone_db_info['user'] }}"
    host: "{{ item }}"
    priv: "{{ openstack_identity_service_keystone_db_info['db'] }}.*:ALL"
    append_privs: true
    password: "{{ openstack_identity_service_keystone_db_info['pass'] }}"
  no_log: true
  become: true
  with_items:
    - '{{ ansible_hostname }}'
    - 127.0.0.1
    - '::1'
    - 'localhost'
    - '%'
