---
# https://docs.openstack.org/ocata/install-guide-ubuntu/keystone-users.html

# Create the default service project
- name: projects | Creating Service Project
  os_project:
    cloud: 'default'
    name: "service"
    description: "Service Project"
    domain_id: "default"
    state: "present"
    enabled: true
